AWSTemplateFormatVersion: "2010-09-09"
Description: "Aplicação que transforma arquivos em Parquet e salva em S3"
Resources:
  Teste:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mybucket/path/to/code
      Handler: index.handler
      Runtime: node

